# Generated by Django 3.2.25 on 2025-12-04 03:25

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/designs/', validators=[catalog.models.validate_image_file], verbose_name='Изображение дизайна'),
        ),
    ]
